S90-URL: http://10.111.222.155:4010/
EAF-URL: http://120.78.122.10:4010/
baidu_url: https://www.baidu.com
juhe_simple_weather: http://apis.juhe.cn/simpleWeather/query
log:
    file_name: test.log
    backup: 5
    consle_level: WARNING
    file_level: DEBUG
    pattern: '%(name)s - %(levelname)s - %(asctime)s - %(message)s'
---
weather_key: de5148ef8cabaf81c0d1c83c84098379